# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[tools]
bun = "1.3.3"
node = "24"

[env]

[tasks]
astro = "bun run astro"
build = "bun run build"
dev = "bun run dev"
preview = "bun run preview"
sync = "bun install"

[tasks.gen-api-docs]
tools.uv = "latest"
run = "uvx ../scripts/gen-api-docs.py"
