# SPDX-FileCopyrightText: 2025 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
# "$schema" = "https://raw.githubusercontent.com/knitli/codeweaver/refs/heads/main/schema/codeweaver.schema.json"

project_path = "."
project_name = "codeweaver-test"
token_limit = 30000
max_file_size = 1048576
max_results = 30

[provider]
agent = [
  { provider = "anthropic", enabled = true, model = "claude-haiku-4.5", model_settings = {  } },
]
data = [
  { provider = "tavily", enabled = true },
  { provider = "duckduckgo", enabled = true },
]
embedding = [
  { provider = "fastembed", enabled = true, model_settings = { model = "BAAI/bge-small-en-v1.5" } },
]
reranking = [
  { provider = "fastembed", enabled = true, model_settings = { model = "Xenova/ms-marco-MiniLM-L-6-v2" } },
]
vector_store = [
  { provider = "qdrant", enabled = true, provider_settings = { url = "http://localhost:6333", collection = "codeweaver-test" } },
]
sparse_embedding = [
  { provider = "fastembed", enabled = true, model_settings = { model = "prithivida/Splade_PP_en_v1" } },
]
